---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - postgresql.pramodhayyappan.dev
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgresql.pramodhayyappan.dev
  resources:
  - roles/finalizers
  verbs:
  - update
- apiGroups:
  - postgresql.pramodhayyappan.dev
  resources:
  - roles/status
  verbs:
  - get
  - patch
  - update
