# permissions for end users to view roles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: postgresql-operator
    app.kubernetes.io/managed-by: kustomize
  name: role-viewer-role
rules:
- apiGroups:
  - postgresql.pramodhayyappan.dev
  resources:
  - roles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - postgresql.pramodhayyappan.dev
  resources:
  - roles/status
  verbs:
  - get
